---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/collections.yml
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: centos-stream8
    image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        kolla_extra_config_path: ${MOLECULE_TEMP_PATH:-/tmp}
        kolla_enable_aodh: true
        kolla_enable_barbican: true
        kolla_enable_blazar: true
        kolla_enable_ceilometer: true
        kolla_enable_cinder: true
        kolla_enable_cloudkitty: true
        kolla_enable_designate: true
        kolla_enable_elasticsearch: true
        kolla_enable_glance: true
        kolla_enable_gnocchi: true
        kolla_enable_grafana: true
        kolla_enable_haproxy: true
        kolla_enable_heat: true
        kolla_enable_horizon: true
        kolla_enable_influxdb: true
        kolla_enable_ironic: true
        kolla_inspector_ipa_kernel_path: ${MOLECULE_TEMP_PATH:-/tmp}/ironic-agent.kernel
        kolla_inspector_ipa_ramdisk_path: ${MOLECULE_TEMP_PATH:-/tmp}/ironic-agent.initramfs
        kolla_enable_kafka: true
        kolla_enable_keystone: true
        kolla_enable_magnum: true
        kolla_enable_manila: true
        kolla_enable_mariabackup: true
        kolla_enable_mariadb: true
        kolla_enable_masakari: true
        kolla_enable_monasca: true
        kolla_enable_murano: true
        kolla_enable_neutron: true
        kolla_enable_nova: true
        kolla_enable_octavia: true
        kolla_enable_prometheus: true
        kolla_enable_sahara: true
        kolla_enable_swift: true
        kolla_enable_storm: true
        kolla_enable_zookeeper: true
  lint:
    name: ansible-lint
scenario:
  name: enable-everything
verifier:
  name: testinfra
  lint:
    name: flake8
